### ISSUE TITLE
Spaces in the script path causes errors while pull in vars.ps1

### ISSUE THREAD

**Issue by equelin** [WahlNetwork/lab-config#1]
Hello,

Using `Invoke-Expression` with a path with spaces like `C:\Program Files\` throw an error.

I think that you can correct this by escaping spaces that might be in $vars:

```PowerShell
# Pull in vars
$vars = (Get-Item $PSScriptRoot).Parent.FullName + "\vars.ps1"
Invoke-Expression ($vars -replace ' ', '` ')
```

If you are interested, I can do that for you with a PR.

**Comment by chriswahl** [comment]
Yes, good catch - please do submit a PR and I'll merge it.
